# Generated by Django 6.0.6 on 2026-07-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_visit_check_in_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='caregiver_photos/'),
        ),
    ]
