# Generated by Django 6.0.6 on 2026-07-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='date_left',
            field=models.DateField(blank=True, help_text='Date the caregiver left the organisation.', null=True),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='employment_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('RESIGNED', 'Resigned'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20),
        ),
    ]
